#!/bin/bash
[ -r /etc/lsb-release ] && . /etc/lsb-release
if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
  # Fall back to using the very slow lsb_release utility
  DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi
printf "\n"
printf "############################################\n"
printf "##      Workshop on Phyloenomics 2017     ##\n"
printf "##              Cesky Krumlov             ##\n"
printf "##         @evomics #evomics2017          ##\n"
printf "############################################\n"
printf "\n\n"
printf "Welcome to %s (%s).\n" "$DISTRIB_DESCRIPTION" "$(uname -r)"
printf "\n"
